/**
 * PDF Generator for Interview Attempt Data
 *
 * Generates beautifully formatted PDF reports from interview attempt data
 */

import jsPDF from 'jspdf'
import { siteConfig } from '@/config/site'

export interface ConversationMessage {
  role: 'user' | 'assistant'
  content: string
  timestamp: string
}

export interface InterviewResult {
  id: string
  overallScore: number | null
  overallFeedback: string | null
  strengths: string[]
  weaknesses: string[]
  recommendations: string[]
  communication: number | null
  knowledge: number | null
  feedback: string | null
  duration: number | null
  vocabularyComplexity: number | null
  emotionalTone: string | null
  wordCountAnalysis: string | null
  questionAnsweringQuality: number | null
  followUpHandling: boolean | null
  answerStructure: string | null
  exampleUsage: boolean | null
  relevantTopicAnswer: boolean | null
  createdAt: Date
}

export interface InterviewAttempt {
  id: string
  startedAt: Date
  completedAt: Date | null
  duration: number | null
  status: string
  createdAt: Date
  interview: {
    id: string
    title: string | null
    companyName: string | null
    position: string | null
    jobDescription: string | null
    interviewType: string | null
    createdAt: Date
    user?: {
      name: string
      email: string
    }
  }
  results: InterviewResult[]
  conversations: Array<{
    id: string
    transcript: string
    messages: ConversationMessage[]
    duration: number
    createdAt: Date
  }>
}

export async function generateInterviewPDF(attempt: InterviewAttempt): Promise<void> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 20
  let yPosition = margin

  // Helper function to sanitize text for PDF rendering
  const sanitizeText = (text: string): string => {
    if (!text) return ''

    // Replace problematic characters with safe alternatives
    return text
      .replace(/Ø<ß¯/g, 'Interviewer')  // Replace corrupted interviewer marker
      .replace(/Ø=Üd/g, 'Candidate')     // Replace corrupted candidate marker
      .replace(/[^\x20-\x7E\n\r\t]/g, '') // Remove non-printable characters except newlines and tabs
      .trim()
  }

  // Helper functions
  const addPageIfNeeded = (height: number) => {
    if (yPosition + height > pageHeight - margin) {
      addWatermark()
      pdf.addPage()
      yPosition = margin
      addWatermark()
    }
  }

  const addWatermark = () => {
    // Add subtle watermark
    try {
      // Simple text-based watermark without advanced graphics
      pdf.setFontSize(60)
      pdf.setTextColor(240, 240, 240) // Very light gray
      pdf.text(siteConfig.name, pageWidth / 2, pageHeight / 2, {
        align: 'center',
        angle: 45
      })
      // Reset text color
      pdf.setTextColor(0, 0, 0)
    } catch (error) {
      // Watermark failed, continue without it
      console.warn('Watermark could not be added:', error)
    }
  }

  const addText = (text: string, fontSize = 10, fontWeight: 'normal' | 'bold' = 'normal', color: [number, number, number] = [0, 0, 0]) => {
    pdf.setFontSize(fontSize)
    pdf.setFont('helvetica', fontWeight)
    pdf.setTextColor(color[0], color[1], color[2])
    pdf.text(text, margin, yPosition)
  }

  const addCenteredText = (text: string, fontSize = 10, fontWeight: 'normal' | 'bold' = 'normal', color: [number, number, number] = [0, 0, 0]) => {
    pdf.setFontSize(fontSize)
    pdf.setFont('helvetica', fontWeight)
    pdf.setTextColor(color[0], color[1], color[2])
    pdf.text(text, pageWidth / 2, yPosition, { align: 'center' })
  }

  const addWrappedText = (text: string, maxWidth: number, fontSize = 10) => {
    pdf.setFontSize(fontSize)
    const lines = pdf.splitTextToSize(text, maxWidth)
    lines.forEach((line: string) => {
      addPageIfNeeded(5)
      pdf.text(line, margin, yPosition)
      yPosition += 5
    })
  }

  // Add watermark to first page
  addWatermark()

  // Title Page
  pdf.setFontSize(28)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(41, 128, 185) // Blue color
  pdf.text('Interview Report', pageWidth / 2, 50, { align: 'center' })

  // Add user name if available
  if (attempt.interview.user?.name) {
    pdf.setFontSize(16)
    pdf.setTextColor(52, 73, 94)
    pdf.text(`for ${attempt.interview.user.name}`, pageWidth / 2, 70, { align: 'center' })
  }

  pdf.setFontSize(18)
  pdf.setTextColor(0, 0, 0)
  pdf.text(attempt.interview.title || 'Untitled Interview', pageWidth / 2, 95, { align: 'center' })

  pdf.setFontSize(12)
  pdf.setTextColor(100, 100, 100)
  pdf.text(`Generated by ${siteConfig.name}`, pageWidth / 2, 115, { align: 'center' })

  pdf.setFontSize(10)
  pdf.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, pageWidth / 2, 130, { align: 'center' })

  // Interview Overview
  pdf.addPage()
  yPosition = margin

  addText('INTERVIEW OVERVIEW', 16, 'bold', [41, 128, 185])
  yPosition += 20

  // Create a clean layout without emojis that cause encoding issues
  const overviewData = [
    ['Interview Title:', attempt.interview.title || 'N/A'],
    ['Interviewee:', attempt.interview.user?.name || 'N/A'],
    ['Company:', attempt.interview.companyName || 'N/A'],
    ['Position:', attempt.interview.position || 'N/A'],
    ['Interview Type:', attempt.interview.interviewType || 'N/A'],
    ['Started:', attempt.startedAt.toLocaleDateString() + ' at ' + attempt.startedAt.toLocaleTimeString()],
    ['Completed:', attempt.completedAt ? attempt.completedAt.toLocaleDateString() + ' at ' + attempt.completedAt.toLocaleTimeString() : 'In Progress'],
    ['Duration:', attempt.duration ? `${Math.round(attempt.duration / 60)} minutes` : 'N/A'],
    ['Status:', attempt.status.charAt(0).toUpperCase() + attempt.status.slice(1)],
    ['Conversations:', attempt.conversations.length.toString()],
    ['Total Messages:', attempt.conversations.reduce((sum, conv) => sum + conv.messages.length, 0).toString()]
  ]

  overviewData.forEach(([label, value]) => {
    addPageIfNeeded(10)
    addText(label, 11, 'bold', [52, 73, 94])
    yPosition += 6
    addText(value, 10, 'normal', [0, 0, 0])
    yPosition += 8
  })

  // Job Description
  if (attempt.interview.jobDescription) {
    pdf.addPage()
    yPosition = margin

    addText('JOB DESCRIPTION', 14, 'bold')
    yPosition += 15

    const sanitizedJD = sanitizeText(attempt.interview.jobDescription)
    addWrappedText(sanitizedJD, pageWidth - 2 * margin, 10)
  }

  // Results & Analysis
  if (attempt.results.length > 0) {
    pdf.addPage()
    yPosition = margin

    addText('ANALYSIS RESULTS', 16, 'bold', [41, 128, 185])
    yPosition += 20

    // Show summary of all results at the top
    const totalResults = attempt.results.length
    addText(`Analysis Summary: ${totalResults} result${totalResults > 1 ? 's' : ''} available`, 12, 'normal', [52, 73, 94])
    yPosition += 10

    attempt.results.forEach((result, index) => {
      if (index > 0) {
        pdf.addPage()
        yPosition = margin
      }

      // Overall Score prominently displayed
      if (result.overallScore !== null && result.overallScore !== undefined) {
        const scoreValue = typeof result.overallScore === 'number' ?
          Math.max(0, Math.min(100, result.overallScore)) : // Ensure score is between 0-100
          0
        
        // Display score with proper spacing
        addCenteredText(`${scoreValue}/100`, 24, 'bold', [41, 128, 185])
        yPosition += 30 // Space after score (24pt font + 6pt spacing)
        
        addCenteredText('OVERALL SCORE', 12, 'normal', [100, 100, 100])
        yPosition += 20 // Space after label
      }

      // Key Metrics
      const metrics = [
        { label: 'Communication Skills', value: result.communication },
        { label: 'Technical Knowledge', value: result.knowledge },
        { label: 'Vocabulary Complexity', value: result.vocabularyComplexity },
        { label: 'Question Quality', value: result.questionAnsweringQuality }
      ]

      metrics.forEach(metric => {
        if (metric.value !== null) {
          addPageIfNeeded(12)
          addText(`${metric.label}: ${metric.value}`, 11, 'normal')
          yPosition += 10
        }
      })

      yPosition += 10

      // Overall Feedback
      if (result.overallFeedback) {
        addText('Overall Feedback:', 13, 'bold', [41, 128, 185])
        yPosition += 12
        const sanitizedFeedback = sanitizeText(result.overallFeedback)
        addWrappedText(sanitizedFeedback, pageWidth - 2 * margin, 10)
        yPosition += 10
      }

      // Strengths
      if (result.strengths.length > 0) {
        addText('Strengths:', 13, 'bold', [34, 139, 34])
        yPosition += 12
        result.strengths.forEach(strength => {
          addPageIfNeeded(8)
          const sanitizedStrength = sanitizeText(strength)
          addText(`• ${sanitizedStrength}`, 10, 'normal', [34, 139, 34])
          yPosition += 8
        })
        yPosition += 5
      }

      // Weaknesses
      if (result.weaknesses.length > 0) {
        addText('Areas for Improvement:', 13, 'bold', [220, 53, 69])
        yPosition += 12
        result.weaknesses.forEach(weakness => {
          addPageIfNeeded(8)
          const sanitizedWeakness = sanitizeText(weakness)
          addText(`• ${sanitizedWeakness}`, 10, 'normal', [220, 53, 69])
          yPosition += 8
        })
        yPosition += 5
      }

      // Recommendations
      if (result.recommendations.length > 0) {
        addText('Recommendations:', 13, 'bold', [23, 162, 184])
        yPosition += 12
        result.recommendations.forEach(recommendation => {
          addPageIfNeeded(8)
          const sanitizedRecommendation = sanitizeText(recommendation)
          addText(`• ${sanitizedRecommendation}`, 10, 'normal', [23, 162, 184])
          yPosition += 8
        })
      }
    })
  }

  // Conversation History
  if (attempt.conversations.length > 0) {
    pdf.addPage()
    yPosition = margin

    addText('CONVERSATION HISTORY', 16, 'bold', [41, 128, 185])
    yPosition += 20

      attempt.conversations.forEach((conversation, convIndex) => {
        addPageIfNeeded(15)

        // Conversation header with time
        const convTime = conversation.createdAt.toLocaleDateString() + ' ' + conversation.createdAt.toLocaleTimeString()
        addText(`Conversation ${convIndex + 1}`, 13, 'bold', [52, 73, 94])
        yPosition += 8
        addText(`Started: ${convTime}`, 10, 'normal', [100, 100, 100])
        yPosition += 12

        // Optional: Add transcript summary if available and clean
        if (conversation.transcript && conversation.transcript.trim()) {
          const sanitizedTranscript = sanitizeText(conversation.transcript)
          if (sanitizedTranscript.length > 0) {
            addPageIfNeeded(8)
            addText(`Transcript: ${sanitizedTranscript.substring(0, 100)}${sanitizedTranscript.length > 100 ? '...' : ''}`, 9, 'normal', [120, 120, 120])
            yPosition += 8
          }
        }

      conversation.messages.forEach((message) => {
        addPageIfNeeded(10)

        const role = message.role === 'user' ? 'Candidate' : 'Interviewer'
        const timestamp = new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })

        // Role and timestamp
        addText(`${role} (${timestamp}):`, 10, 'bold', message.role === 'user' ? [34, 139, 34] : [41, 128, 185])
        yPosition += 7

        // Message content with indentation - sanitize to prevent encoding issues
        const sanitizedContent = sanitizeText(message.content)
        const indentedContent = '  ' + sanitizedContent
        addWrappedText(indentedContent, pageWidth - 2 * margin - 10, 9)
        yPosition += 8
      })

      yPosition += 15 // Space between conversations
    })
  }

  // Add footer to all pages
  const totalPages = pdf.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i)
    pdf.setFontSize(8)
    pdf.setTextColor(150, 150, 150)

    // Footer with branding
    const footerText = `Generated by ${siteConfig.name} - ${siteConfig.url}`
    const footerWidth = pdf.getTextWidth(footerText)
    pdf.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10)

    // Page number
    const pageText = `Page ${i} of ${totalPages}`
    pdf.text(pageText, pageWidth - margin - pdf.getTextWidth(pageText), pageHeight - 10)
  }

  // Save the PDF
  const fileName = `interview-report-${new Date().toISOString().split('T')[0]}.pdf`
  pdf.save(fileName)
}
